name: Epic Completion Detection
on:
  push:
    branches:
      - 'epic-*-*'

jobs:
  detect-epic-completion:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Epic') && contains(github.event.head_commit.message, 'Complete')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract epic number
        id: extract-epic
        run: |
          # Extract epic number from commit message
          EPIC_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -o 'Epic [0-9]*' | grep -o '[0-9]*')
          echo "epic_number=$EPIC_NUMBER" >> $GITHUB_OUTPUT
          
          # Extract epic name from branch
          BRANCH_NAME="${{ github.ref_name }}"
          EPIC_NAME=$(echo "$BRANCH_NAME" | sed 's/epic-[0-9]*-//')
          echo "epic_name=$EPIC_NAME" >> $GITHUB_OUTPUT
          
          echo "Detected Epic $EPIC_NUMBER completion: $EPIC_NAME"
      
      - name: Create epic completion PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create PR to main with epic-complete label
          gh pr create \
            --title "Epic ${{ steps.extract-epic.outputs.epic_number }} Complete" \
            --body "Epic ${{ steps.extract-epic.outputs.epic_number }}: ${{ steps.extract-epic.outputs.epic_name }} has been completed.
          
          ## Epic Summary
          - **Epic Number:** ${{ steps.extract-epic.outputs.epic_number }}
          - **Epic Name:** ${{ steps.extract-epic.outputs.epic_name }}
          - **Completed:** $(date +%Y-%m-%d)
          
          ## Next Steps
          - [ ] Review the changes
          - [ ] Merge this PR
          - [ ] Devlog post will be automatically generated
          - [ ] Review and enhance the generated post" \
            --label "epic-complete" \
            --base master
